services:
  mysql:
    image: 'mysql:latest'
    container_name: 'local-mysql2'
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'admin'
      MYSQL_USER: 'test'
      MYSQL_PASSWORD: 'test'
      MYSQL_DATABASE: 'e-commerce'